services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: ci_app
    networks:
      net_private:
        ipv4_address: 192.168.99.4
    volumes:
      - .:/var/www/html
      - ./docker/app/fail2ban:/etc/fail2ban
    depends_on:
      - node
    # restart jika ingin otomatis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: ci_nginx
    ports:
      - "83:80"
    networks:
      net_private:
        ipv4_address: 192.168.99.8
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/app/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app

  node:
    build:
      context: ./docker/node
    container_name: ci_node
    restart: unless-stopped
    volumes:
      - ./docker/node:/usr/src/app
    working_dir: /usr/src/app
    command: ["pm2-runtime", "process.yml"]
    ports:
      - "84:3000"
    networks:
      net_private:
        ipv4_address: 192.168.99.9

networks:
  net_private:
    external: true
