version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: ci_app
    volumes:
      - .:/var/www/html
      - ./docker/app/fail2ban:/etc/fail2ban

  nginx:
    image: nginx:alpine
    container_name: ci_nginx
    ports:
      - "83:80"
    networks:
      net_private:
        ipv4_address: 192.168.99.8
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
      
  node:
    build:
      context: ./docker/node
    container_name: ci_node
    restart: unless-stopped
    volumes:
      - ./docker/node:/usr/src/app
    working_dir: /usr/src/app
    command: ["pm2-runtime", "process.yml"]
    ports:
      - "3000:3000"
    networks:
      - ci-network

networks:
  net_private:
    external: true
